# Generated by Django 4.2 on 2025-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_vendor_invoice_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach supporting files for this dispute (PDF, image, etc.)', null=True, upload_to='disputes/'),
        ),
    ]
