# Generated by Django 4.2 on 2025-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_dispute_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
